name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref and github.ref_name
        run: |
          echo "Full ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Repo: ${{ github.repository }}"
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Running OS ${{ runner.os }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Workspace: ${{ env.GITHUB_WORKSPACE }}"
          echo "Temp Directory: ${{ runner.temp }}"
          echo "Tool Cache Directory: ${{ runner.tool_cache }}"
      - name: Job status
        if: ${{ job.status == 'success' }}
        run: echo "Job success!"
